database:
  user: "root" # database user
  password: "12345678" # database user password
  host: "127.0.0.1:3306" # database host including port
  name: "my_cfhn_presence_stats" # database name
server:
  port: 8088
  debug: true
presence_api:
  server: "https://presence.my.cfhn.it/presence/" # API endpoint
  login: "https://login.my.cfhn.it/login/token.json" # Login endpoint
  user: "username"
  password: "password"
